services:

  nginx:
    image: nginx:alpine
    ports:
      - "84:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network
    restart: unless-stopped

  php: &php-template
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - network
    restart: unless-stopped

  redis:
      image: redis:7-alpine
      ports:
          - '6379:6379'
      volumes:
          - redis-data:/data
      networks:
          - network
      restart: unless-stopped
  
  supervisord:
    <<: *php-template
    container_name: supervisord
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/Moscow
    command: ["/usr/bin/supervisord"]
    restart: unless-stopped


  
#   mysql:
#     image: mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: myapp
#       MYSQL_USER: user
#       MYSQL_PASSWORD:
#     ports:
#       - "33061:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
networks:
    network:
      driver: bridge

volumes:
    mysql:
        driver: local
    redis-data:
        driver: local
